apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          image: nginx
          envFrom:
          - configMapRef:
              name: sql-postgresql
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"