apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mutix
resources:
  - deployment.yaml
  - service.yaml
commonLabels:
  app: covid19
  app.kubernetes.io/name: covid19
  app.kubernetes.io/instance: covid19